# Changes here will be overwritten by Copier
_commit: 6ea1260
_src_path: https://github.com/browniebroke/cookiecutter-pypackage
add_me_as_contributor: false
copyright_year: '2024'
documentation: true
email: marhje52@gmail.com
full_name: Martin Hjelmare
github_username: MartinHjelmare
has_cli: false
initial_commit: false
is_django_package: false
open_source_license: Apache Software License 2.0
package_name: aioopenexchangerates
project_name: aioopenexchangerates
project_short_description: Fetch rates from openexchangerates with aiohttp.
project_slug: aioopenexchangerates
run_poetry_install: false
setup_github: false
setup_pre_commit: true

